# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jason Kim
email: iamjsonkim@gmail.com
description: >
  Writings on software and other topics
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jasonkim.ca" # the base hostname & protocol for your site
full_name: Jason Kim
twitter_username: jasoki
github_username:  serv
linkedin_username: jason-kim-a2b97b6

# Build settings
markdown: kramdown

# Jekyll
permalink: /blog/:year/:month/:day/:title/
